### ISSUE TITLE
Search 1st Slice:  UI Changes

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1011]
## User story:
As a user tester, I would like to see the UI changes that Emily has in her mock before the search development begins

## Objective:
The goal is to see the changes in the mocks on the new Search URL

## Ticket background:
One of our attorney's asked for a complex search that involved multiple spellings of a location, multiple keywords and multiple states. We also saw a lot of efficiency come from the Power Keyword Search workaround. Lastly, we wanted to attract a new user group for the Portal: attorneys who would have very specific and complex queries. All of this led us to the idea of making a more robust keyword search.

## Acceptance criteria:
Working off of Emily's Mock: See Emily mock: https://gsa.invisionapp.com/console/share/XC2X84XU5W/734451939

- [ ] Make the changes listed below on the new Search URL 

UI changes:
- [x] Move CRT Summary from level 1 to level 4
- [x] Move Assignee from level 2 to level 1
- [x] Move Incident Location from level 2 to level 1
- [x] Change Incident Location to Incident City/State
- [x] Move Personal Description from level 2 to level 5
- [x] Move incident location from level 2 to level 4
- [ ] Move Reported Reason from level 3 to level 2
- [ ] Move Relevant Details from level 3 to level 2
- [ ] Move Hate Crime from level 3 to level 2
- [ ] Move Contact Email from level 4 to level 3
- [ ] Move contact Email up from level 4 to level 3

**Comment by randyabramson** [comment]
Blocked until other questions are answered (final mocks, etc.)

**Comment by randyabramson** [comment]
@billyhunt  @ilodidoj  We would like to write up ACs for this card in the Wednesday meeting with you. We're not sure if you need ACs for each filter combination, etc.

**Comment by randyabramson** [comment]
Depending on And/Or decision, these might be the final mocks. See changes above:
https://gsa.invisionapp.com/console/share/XC2X84XU5W/734451939

**Comment by louh** [comment]
@randyabramson @emilycryan I've done a first pass at moving UI elements around, and have some clarifying questions / sanity-checking questions to send along.

1. There are two "incident location" changes. One is to change it to "incident city/state" and move it from level 2; the other is to change it to a free-text box and move it to level 4. It would seem strange to do both. One interpretation of this mockup is to split the existing dropdown into two fields, but please confirm what you'd like to do here.

![Screenshot 2021-08-19 at 11-43-10 CRT Advanced Search, Initial Version - Play](https://user-images.githubusercontent.com/2553268/130099706-32c4aadb-a14f-48ce-bd6e-dd054a460e54.png)

2. Levels 3 and 4 are not strictly defined rows. Although there are two separate rows in the mockup, on large enough monitor resolutions, our current layout will render this on one row. It only renders as multiple rows because the window width forces it to break into two. For instance:

![Screenshot 2021-08-19 at 11-46-55 Contact the Civil Rights Division Department of Justice](https://user-images.githubusercontent.com/2553268/130100147-5c68e63c-07a2-4c53-96f8-247a8803c299.png)

Please confirm if this is acceptable, or if the intent is to always have 2 rows here, even at higher resolutions. (Please note that each row will continue to break into "more rows" if the window has less width, e.g. if a user resizes their browser window or is accessing via a mobile device.)

3. On the current version of our filters, everything below the second row only appears under "more filters." Based on the mockup, I'm interpreting that the "Personal description" row is "special" and always appears, even when there are less filters. Is this a correct assumption? (In my screenshots so far, the "Personal description" input has not yet been restyled to match the mockup.)

"More filters" collapsed:
![Screenshot 2021-08-19 at 11-51-42 Contact the Civil Rights Division Department of Justice](https://user-images.githubusercontent.com/2553268/130101072-938b7f6c-773d-469d-a697-66a692478cad.png)

"More filters" expanded:
![Screenshot 2021-08-19 at 11-51-33 Contact the Civil Rights Division Department of Justice](https://user-images.githubusercontent.com/2553268/130101390-faa8b586-a29c-4212-a313-a9e747df2757.png)

**Comment by louh** [comment]
4. Currently, the "Primary issue", "Reported reason" and "Relevant details" dropdowns are set to be wider than the default width. In order to match the new UI mockup more closely, and to fit "Primary issue", "Reported reason" and "Relevant details" dropdowns in the second row (Level 2), the custom widths have been removed. Were the custom widths set in response to previous feedback or previous designs, and are we losing anything by going back to default widths?

**Comment by emilycryan** [comment]
@louh I can answer most of these! For item 1, we are actually doing two things - splitting the current dropdown which contains city, state AND location into a dropdown for city/state and a separate field for location name bc this the location field will eventually be searchable just like personal description is. Since we're moving things about at this point, it makes the most sense to break this out NOW and get users used it along with the other UI changes. It's the only change about more than moving a field around but it sets us up and the users to think about these in the context of the broader need to do a full text search of location name. 

For items 2 and 3, the resizing is weird but it seems to have worked with our audience so I'd suggest we stick to the same layout but essentially reordering which would "bump" fields into rows 3 and 4 on smaller monitors but ultimately not change the way in which it was originally designed. As for the MORE / LESS the original thought when we had two pages (current search and new search) was to keep the drawer open by default (i.e., in the MORE state) so that users could quickly get to keywords searching for early pilot testing. Now I'm not sure how we should handle it - it's already way too big when it's open and impedes seeing results quickly. Perhaps @randyabramson or @blaughman have thoughts here... 

HTH

**Comment by emilycryan** [comment]
As for item 4, @louh keeping them as is is fine for now - I have problems with the default width. I believe I was using an old mockup more to show IA and not visual design (since I am most def not a visual designer) So go with what is being used already. CC @randyabramson @blaughman

**Comment by louh** [comment]
Thank you @emilycryan. I will have city/state and location name split into separate inputs, and we can review the other stuff when the branch is ready (soon!)

**Comment by louh** [comment]
Decisions from standup today. The following "live updates" were done in browser:

<img width="1198" alt="Screen Shot 2021-08-20 at 12 52 50 PM" src="https://user-images.githubusercontent.com/2553268/130267552-7dfa26fc-d4d1-40f0-aa12-3e3bdab64a9c.png">

Proposed changes:
- Move "Contact Email" to second row, below "Contact First Name" (closer grouping with name search)
- Move "Hate Crime" next to "Prison Type"
- Move "CRT Summary" and "Incident Location" text input boxes next to "Personal Description"
- Remove More/Less functionality
- Move "Apply filters" button below filters

We would like to try this new UI out to see how users use filters.

Future actions:
- Consider merging "Personal Description", "CRT Summary" and "Incident Location" into one search box.

**Comment by emilycryan** [comment]
@louh winner winner, chicken dinner! Love it - thank you for doing it real time and letting us collab on it. It's *awesome* CC @randyabramson @blaughman

**Comment by randyabramson** [comment]
"Consider merging "Personal Description", "CRT Summary" and "Incident Location" into one search box." = mind blown @emilycryan @louh @blaughman

**Comment by blaughman** [comment]
All the filters are working as expected.  One issue I found was the 'Primary Issue' filter tiles populate to the left of the status tiles.  On all other filters, the tiles appear to the right of the status tiles. @randyabramson @louh @billyhunt @ilodidoj 

![image](https://user-images.githubusercontent.com/52507395/130638455-6863f301-9076-4363-9754-994fd3245c5b.png)

**Comment by emilycryan** [comment]
Solid catch @blaughman The tiles should appear in the order in which they are listed as filters. CC @louh @billyhunt @randyabramson @ilodidoj

**Comment by randyabramson** [comment]
@billyhunt One thing I see is that a search for 'hy vee' brings up results for 'hy vee' AND 'hy-vee.'

@blaughman @emilycryan

**Comment by emilycryan** [comment]
@billyhunt yes, exactly. We only need to worry about that happening for very specific, quote strings where exact match is expected. Otherwise, this functions as it should @randyabramson

**Comment by louh** [comment]
I'm moving the filter display around and noticed some things we might want to address.

The first is that "Incident location" is used in two places to label different things. In the filters, "incident location" is a free-form text field for the location name. In the table below, "incident location" is the label for city/state. This might be confusing for people? I confused myself when testing a location search!
![Screenshot 2021-08-24 at 11-42-50 Contact the Civil Rights Division Department of Justice](https://user-images.githubusercontent.com/2553268/130647972-a6fdf075-4c64-4c82-b11f-05825883e565.png)

There are some discrepancies in the UI which predates this issue so if it's worth tackling let me know if we want to take care of it here, or in a followup card.

The dropdown on the "Incident city/state" has two labels: "Incident location city" and "Location state". I think the inconsistent labels makes my eye twitch just a little. Could we standardize to use the same phrasing? e.g. update "Location state" to "Incident location state", or better yet, simplify both to "City" and "State".
<img width="336" alt="Screen Shot 2021-08-24 at 11 45 36 AM" src="https://user-images.githubusercontent.com/2553268/130648058-fcf781ce-7c23-4a1a-a43b-f8dfd26b5035.png">

I re-ordered the filters and activated every single one to make sure they match the input order. But I encountered some inconsistent labeling:

<img width="1210" alt="Screen Shot 2021-08-24 at 11 41 08 AM" src="https://user-images.githubusercontent.com/2553268/130648524-f942c12e-2473-494b-b245-04428cba4410.png">

- "ID" and "Complaint ID" - inconsistent label text
- "create date start" and "create date end" - inconsistent capitalization
- "Servicemember" and "Service member" - inconsistent word spacing
- "correctional facility type" and "Prison Type" - inconsistent label text
- "Summary" and "CRT Summary" - inconsistent label text
- "Location name" and "Incident location" - inconsistent label text

I'd love to be able to make these consistent between the bits of UI.

**Comment by louh** [comment]
Since https://github.com/usdoj-crt/crt-portal/pull/940 was already merged yesterday (pertaining to moving the filter UI), and we have some related but discrete follow up tasks, I'm going to call this particular ticket "done" but break out the following three items into separate tickets for us to track:

- Moving the filter "tabs" or "pills" around to match the filter order
- Updating some "incident name" and "incident city/state" labels for better consistency
- Updating the filter "pill" labels for better consistency

(Links to each follow-up issue forthcoming.)

**Comment by louh** [comment]
> That makes some sense. There is something called Stemming built into the system. So run, would return "run", "running", "ran", etc. It also gets rid of common words like "and", "a", and "or". I would think when we implement the phrase search (using quotes), we might want to search for the exact phrase. @emilycryan, thoughts?

@billyhunt I broke out some of the other threads of this discussion into separate tickets. Is this a separate ticket? Or did we already resolve the decision here?

**Comment by billyhunt** [comment]
I think this issue will be taken care of when we implement a Phrase search.  I am not sure if there is a ticket for it yet.

**Comment by blaughman** [comment]
@louh @billyhunt @ilodidoj @randyabramson @emilycryan When testing this, the issue I previously mentioned persists.  In fact, I used Emily's feedback and took this to another level of testing.  I ran multiple filters at once and there is no rhyme or reason for the ordering of the tags below the filters.
![image](https://user-images.githubusercontent.com/52507395/130812182-15adae6b-7b04-427d-8cc4-3d01fd488c63.png)

**Comment by blaughman** [comment]
@louh @billyhunt @ilodidoj @randyabramson @emilycryan With that said, we can create a new card for the tag ordering since it was not part of the AC's for this card.

**Comment by emilycryan** [comment]
@blaughman Your search also shows why it's really important to order the tags correctly b/c all drop-downs lack any indicator that something has been entered into that particular filter so someone could spend time trying to locate exactly where they specified the city and state. Once the drop down is closed, it's "out of sight, out of mind" and can be a pain to locate in order to change it. CC @randyabramson @ilodidoj @louh @billyhunt

**Comment by louh** [comment]
@blaughman The new card is here: https://github.com/usdoj-crt/crt-portal-management/issues/1035

Were you able to test on this branch? https://github.com/usdoj-crt/crt-portal/pull/946 (The sorted active filters change is here.)

**Comment by blaughman** [comment]
Filters appear as intended and are working as intended.  Ready for Production.

**Comment by randyabramson** [comment]
Filter order arranged as intended. Closing.
