### ISSUE TITLE
SPIKE - messaging banner on home page

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1047]
Background: The front office is potentially looking to add messaging to the civilrights.justice.gov home page that lets users know they are in the right place to file specific kinds of complaints that our teams generally handle and may be relelvant to big happenings in the news,

Geronimo prepared a mock of a banner that might work for our purposes (see bottom of this card).

We are looking for the DEVs to do research around implementing this messaging on the homepage.

- What is the level of effort?
- Are there any risks?
- Beyond text and translations, what do you need to do your work?

Assumptions: 

- Banner will expand if extra words are added to message
- Message area may or may not include button
- Message area will be responsive for mobile, tablet and desktop view
- Message area will serve up appropriate provided transaltions in response to user selecting a particular language or a language settting in the browser

<img width="933" alt="messaging banner" src="https://user-images.githubusercontent.com/6254621/131890776-3cae3cb8-0971-4073-897b-7c3e14186a96.PNG">

**Comment by randyabramson** [comment]
@louh  @billyhunt  - thanks for your progress on this. I'd like for you to let us know your progress and cap the work for just Thursday...please go back to Email work on Friday.

**Comment by louh** [comment]
I wanted to present a couple of options on the front end. The first one is trying to get as close as possible to my interpretation of the mockup.

<img width="1389" alt="Screen Shot 2021-09-02 at 5 02 59 PM" src="https://user-images.githubusercontent.com/2553268/131915908-11048aae-1904-4478-a5c5-e5c81765eab4.png">

The text size on the message matches the text on the hero. This makes it quite a large banner -- it really presents itself as the most important thing on the page. The button is aligned to the right side of the content container, so it kind of "floats" out there.

The second alternative sets the text size back to the page's default size, and changes the button to a link. It's a lot more subdued, but the yellow banner itself still stands out without being as attention-grabbing as possible.

<img width="1388" alt="Screen Shot 2021-09-02 at 5 03 43 PM" src="https://user-images.githubusercontent.com/2553268/131915986-4887122c-20f3-44bd-a745-51a0b63d8dfc.png">

Using a link instead of a button makes it closer to what it actually does ("go see this page" instead of "do something with user interface"), fits better if the banner is normal-text size, and also puts the call to action closer to the text instead of floating on the right. The design is actually almost exactly the same as the banner used for a similar reason on the USWDS website itself:

<img width="1385" alt="Screen Shot 2021-09-02 at 3 56 58 PM" src="https://user-images.githubusercontent.com/2553268/131915347-e76cf045-a41c-4341-8183-7290e566aeb4.png">

My personal preference is to use link text instead of a button, and I'm ambivalent about the text size.

**Comment by randyabramson** [comment]
This is great work @louh. I think having the larger text size and the link might be the right combination here. (btw, having both the 'get help now' and 'learn more' calls to actions looks odd now that I'm reading it. We should fix that for the hate crimes project).

CC: @blaughman @emilycryan

**Comment by blaughman** [comment]
@ilodidoj @billyhunt @louh @randyabramson @emilycryan  I assume we can close this card since we have proof of concept?

**Comment by billyhunt** [comment]
Yes!  And then some!
