### ISSUE TITLE
IER Form Letter (Korean)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1062]

**Comment by blaughman** [comment]
[Draft IER referral response for portal (Korean).docx](https://github.com/usdoj-crt/crt-portal-management/files/7462533/Draft.IER.referral.response.for.portal.Korean.docx)

**Comment by blaughman** [comment]
[Korean IER Form Letter.docx](https://github.com/usdoj-crt/crt-portal-management/files/7462563/Korean.IER.Form.Letter.docx)

**Comment by louh** [comment]
I do have one question. The translator has again been really helpful in pointing out where some of the way we structure content doesn't work as well when translated to Korean, because their verb/subject structure is reversed in comparison to English. The string for "TO FIND…" was translated as "...을/를 찾으려면", with leading ellipsis instead of trailing ellipsis, because the text should occur at the _end_ of the sentence. The translator notes that they instead wanted to translate to "what I want to find" but I'm not sure if it's in the document. They note that the actual form letter itself was also translated, but is that a separate document from the provided table?

One other implementation note, the translator has pointed out that "Director, Office of Field Management Programs" was included in English as well so that a letter could reach the right person. I've gone ahead and made that implementation the same across all languages where needed.

**Comment by randyabramson** [comment]
@louh  do you want to code the page and then we can do a screen share with a translator?

Thank you for being so attentive with this.

**Comment by louh** [comment]
Yep, we can do that. The letter is already ready to review, let's set up some time.

**Comment by louh** [comment]
After reviewing with the translator, the "To find ... / Organization that may be able to help" sections changed like so:

From:

```
...을/를 찾으려면:

개인 변호사

도울 수 있는 기관:

미국 변호사 협회

    www.findlegalhelp.org
    전화 연락: 1-800-285-2221
```

to: 

```
개인 변호사를 찾으려면:

도울 수 있는 기관:

미국 변호사 협회

    www.findlegalhelp.org
    전화 연락: 1-800-285-2221
```

Essentially, `...을/` portion at the beginning of `...을/를 찾으려면:` was removed, and the remainder was moved to after the type of attorney to be found, in order to preserve Korean word order.

**Comment by randyabramson** [comment]
Korean translation:

[1405587.Korean.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7669590/1405587.Korean.final.docx)

**Comment by blaughman** [comment]
Letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Letter appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letter appears as intended in Production.  Closing this card.
