### ISSUE TITLE
Hate Crime 1 - Remove hate crime question

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1070]

**Comment by blaughman** [comment]
## Narrative
As a product owner, I want to remove the hate crime question so those complaints are properly directed to the FBI.

## Background
The public has  been submitting hate crime complaints since the launch of the portal.  Most of these complaints are actually not hate crimes as defined in US criminal code.  The Criminal Section spoke with the FBI and they are happy to take in hate crime reports and reach out to CRT if the situation warrants.

## Acceptance Criteria
1) Given I am on page 2 of the complaint form
when I select a primary concern and click 'Next'
then I am on the 'Location details' page

**Comment by randyabramson** [comment]
NOTE: Blocked until the Hate Crime banner and Hate Crime page are live

**Comment by blaughman** [comment]
Question is removed in Chrome, Edge and Mobile in Production.  Closing this card.
