### ISSUE TITLE
District Number Definitions

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1098]
## User story:
As a CRT user, I want the geographic locations listed so that I can easily determine the district for the location of the incident.

## Objective:
CRT users will be more efficient processing records

## Ticket background:
Legacy Systems listed the description next to the district number. This made users more efficient knowing what court system to file in as well as which office to contact when communicating with other government entities.
![image](https://user-images.githubusercontent.com/52507395/135919689-28605a81-bb1e-4004-bb0b-475e4787b16b.png)

## Acceptance criteria:
1. Given I am on the complaint detail page in the actions card
when I select the 'judicial district' dropdown
then I see the district numbers and a geographical description next to the number

## Assumptions
- A screen reader should read "1, Alabama - ND"
- A nice to have - Screen reader would read the following "ND - Northern District, SD - Southern District, MD - Middle District, ED - Eastern District, WD - Western District"
[District Numbers and Definitions.xlsx](https://github.com/usdoj-crt/crt-portal-management/files/7281105/District.Numbers.and.Definitions.xlsx)

**Comment by louh** [comment]
@blaughman Questions:

- Our portal only has district choices up to 90 (Virgin Islands), the spreadsheet includes districts past 90 (up to 106 for Iraq). Can you confirm whether I only use existing district choices, or add the missing ones?
- The bulk actions form displays a "Judicial district" select box that is disabled by default, and I can't seem to find a way to re-enable it through the UI. Is that intentional?

**Comment by ilodidoj** [comment]
> @blaughman Questions:
> 
> * Our portal only has district choices up to 90 (Virgin Islands), the spreadsheet includes districts past 90 (up to 106 for Iraq). Can you confirm whether I only use existing district choices, or should I add the missing ones as well?
> * The bulk actions form displays a "Judicial district" select box that is disabled by default, and I can't seem to find a way to re-enable it through the UI. Is that intentional?

@louh @billyhunt "Judicial District" must not be included in the bulk action.  It can have adverse impact of incorrectly overwrite the current "Judicial District" of an existing report.

**Comment by blaughman** [comment]
@louh @ilodidoj @billyhunt  Let's only include the definitions for the existing district numbers currently in the portal. Sorry if the sheet was confusing.  I was going off the list in a legacy system.

**Comment by louh** [comment]
@blaughman I looked into the "nice to have" (getting the screen reader to read acronyms like "ND" as "Northern District").

Screen-reader text is essentially a third piece of information, but we use Django's built-in form builder that only takes two (the id number and a text label).

If we want to hit the "nice to have", we basically have two options:

1. Re-implement the select dropdown with a custom form builder that accepts a screen-reader label (very high level of effort)
2. Change the text labels to use long text instead of acronyms (low level of effort)

What do you think?

@billyhunt Do you have any thoughts on this as well?

**Comment by louh** [comment]
Following up from above: I have a possible theory on how to do this that doesn't involve re-implementing the dropdown from scratch.

**Comment by louh** [comment]
@blaughman I did a test with NVDA, and I cannot get it to read text that's different from what's displayed as a select option.

**Comment by blaughman** [comment]
Functions as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Function working as intended in Production.  Closing this card.
