### ISSUE TITLE
Housing form letter

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1112]
Source of truth
[HCE Form Letter - English.docx](https://github.com/usdoj-crt/crt-portal-management/files/8072678/HCE.Form.Letter.-.English.docx)

**Comment by blaughman** [comment]
This will replace the existing HCE referral letter currently in the contact complainant menu.  I would like @chinelo-ikejimba to check this over since there is a table on the document.  This might be our first use case for the table to be a link to a standalone page (clickable from the form letter).

**Comment by blaughman** [comment]
Updated form letter.  List of resources will be a standalone page.  
[HCE.Letter corrected resources.docx](https://github.com/usdoj-crt/crt-portal-management/files/8044076/HCE.Letter.corrected.resources.docx)

**Comment by blaughman** [comment]
@billyhunt Feedback from HCE, "I have three proposed edits that are highlighted below: the first should be a comma and not a semicolon, the second inserts a hyphen into “Housing-related,” and the third highlights the link to the ABA page—this is the broken link that we fixed on the resources page (the http vs. https issue)."

![image](https://user-images.githubusercontent.com/52507395/156766208-ec0eba48-7faf-4e61-a86c-99e9688c2850.png)

**Comment by blaughman** [comment]
Confirmed by HCE staff (AB), the letter appears as intended and is sending properly.  Closing this card.
