### ISSUE TITLE
Placeholder - SPIKE - Quotes on Search - prioritizing AND/OR

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1165]
Spike on quotes on search/ordering - https://github.com/usdoj-crt/crt-portal-management/issues/1161 And/OR ordering

**Comment by randyabramson** [comment]
@louh  - these sample links work for me, but only if I cut/paster into EDGE (clicking brought up some authentication stuff)

Again, we were trying to search for reports that had the word 'veteran' AND 'lease' OR 'posession'...here's that search:

https://crt-portal-django-prod.app.cloud.gov/form/view/?status=new&status=open&violation_summary=lease%20OR%20repossession%20AND%20veteran&no_status=false

And here's a result that came up in that search that did not contain the word 'veteran'

https://crt-portal-django-prod.app.cloud.gov/form/view/122669/?next=%3Fper_page%3D15%26status%3Dnew%26status%3Dopen%26violation_summary%3Dlease%20OR%20repossession%20AND%20veteran%26page%3D1&index=0

**Comment by ilodidoj** [comment]
@randyabramson @louh @billyhunt I think the actual search term is: search for reports that had the word ( 'veteran' AND 'lease' ) OR (  'veteran' AND 'posession' ) .

**Comment by louh** [comment]
I think the best way of getting the search functionality we want is to use Django's own plugin that uses PostgreSQL's built-in text search functionality (https://docs.djangoproject.com/en/3.2/ref/contrib/postgres/search/#searchquery). The "websearch" functionality allows us to use AND, OR, NOT, "exact phrase with quotes" and (parentheses for grouping order of operations).

However: this functionality is only available in Django v3.2+ (we are on v2.2) and PostgreSQL v11+ (we are on v10).

Updating Django and PostgreSQL will feel like side-quests that aren't directly implementing this feature, _but_ we will need to do these upgrades soon anyway. Django v2.2 reaches [end of extended support](https://www.djangoproject.com/download/#supported-versions) in April 2022 (just a few months), and PostgreSQL v10 reaches [end of support](https://www.postgresql.org/support/versioning/) in November 2022, just under a year. Once these updates have been made, using the built-in search functionality will be vastly better than any home-grown reinvention of the wheel we can build in the same time frame.

As a result, I'd suggest planning for this sequence of tasks:

1. Update Django to v3.2. Django recommends we do incremental upgrades, so jumping ahead to v4 at this point may be premature.
2. Update PostgreSQL to v12, the highest version currently supported by cloud.gov [according to their documentation](https://cloud.gov/docs/services/relational-database/). Imran believes we can jump ahead without much issue because we do not have a highly customized/specialized database needs. Note that this involves coordination with cloud.gov support.
3. Finally, implement text search with just a few lines of code.

I estimate each task taking one sprint to do each with focused effort, and no more than two, assuming all goes well.

**Comment by randyabramson** [comment]
Thanks for the details above @louh !! Are there any risks that you know of that you want to lay out in this ticket.

Thanks!

**Comment by ilodidoj** [comment]
@randyabramson @louh @billyhunt I totally agree with @louh Lou's approach to this and the tasks sequence he laid out.  I am sceptic on creating home grown search workarounds; that creates possibilities of SQL injection and add to the security risks.  Taking the route of tools both Django and Postgres do the job is more appropriate and less risky IMHO. At the end of the day the most we will be able to do is what a specific version of Postgres offers for search and that is supported on cloud.gov current service level.

**Comment by billyhunt** [comment]
+1

**Comment by blaughman** [comment]
Closing this card.
