### ISSUE TITLE
Explore updated form letter responses with links, formatting, etc.

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1170]
## User story:
As a product owner, I want form letter responses with links and tables.

## Objective:
Determine if these features are feasible.

## Key result:
Better messaging with the public (increase public trust/experience)

## Ticket background:
Currently, our form letter responses are not able to produce links or present tables when messaging the public.  Incorporating these features will produce more professional messaging.

**Comment by blaughman** [comment]
#863 Previous card for HTML messaging.

**Comment by louh** [comment]
It seems that our major concerns around HTML emails can be boiled down to two major questions.

1. **Can we do this, from a technical standpoint?** Yes. As HTML emails are more common and widespread, _technical implementation_ is possible (e.g. our third-party mail delivery provider, GovDelivery TMS, [supports HTML emails](https://developer.govdelivery.com/api/tms/tutorial/use_email_templates/)). I'll outline a more detailed process for how we can do this specifically in a follow up post.
2. **Could HTML emails under-serve a population of viewers that cannot read them?** I suspect there are two types of populations we might be concerned about:
    - The "digital divide": what percentage of people can only receive plain-text emails, and cannot display HTML emails at all? If a significant population of our users might fall into this category, we may decide to stick with plain-text emails to ensure readability for the widest possible audience. I would like our team to make this decision based on market research and data, and I'm looking into it. 
    - People with disabilities. This is an accessibility question. Just as we design websites for accessibility, HTML emails should have similar concerns and guidelines to account for. This might be a question for Terri to offer recommendations and guidance.

I've checked in with another project team at Nava which are sending HTML emails. Their use of HTML follows Mailchimp's [Limitations of HTML email](https://mailchimp.com/help/limitations-of-html-email/) guidance which describes what can and cannot be incorporated into an HTML email. Based on my observation of the design in #863, I don't expect anything we're looking for to fall outside of this guidance.

More to come.

**Comment by randyabramson** [comment]
Thank you for your good thoughts on this @louh. I might ask some folks on JMD that send out mails if they ever send out HTML versions.

**Comment by louh** [comment]
And now, a summary of what I think we need to do to implement form letter responses in HTML:

- **Form letters can be formatted in [Markdown](https://www.markdownguide.org/getting-started/).** Markdown is basic text formatting to indicate bold, italics, links, headers, tables, lists, and a few other things, and can be converted easily to HTML. Existing letters can be upgraded to use Markdown, and letters that aren't upgraded will continue to work as-is, so there is no pressure to upgrade everything at once.
- **The “Contact complainant” preview will be updated to render HTML instead of plain text.** Each of the various contact actions can work with HTML. (If I'm missing one, please let me know.)
  - **For copying to clipboard,** the copy-paste action will include the formatting. Users can paste plain text without formatting by using Shift-Ctrl-V to paste.
  - **For printing,** it should work as-is, since the page is built with HTML already.
- **Form letter e-mails can be sent in a "multipart" format that contains both HTML and plain text.** We'll render the content as HTML and insert it into a custom HTML template to match the design in #863. We'll follow best-practice guidelines to ensure compatibility with email clients and for accessibility. GovDelivery TMS will automatically convert the HTML email to a text format and send a "multipart" type email. Email clients that cannot view HTML will automatically display the plain text content. (This has been the experience of another Nava project that uses TMS, but we may also want to confirm directly with GovDelivery. See below.)
- **Markdown parsers will need to be installed in both the front-end and back-end,** unless the front-end is updated to allow fetching form letter content from the server asynchronously. Right now, all form letters are embedded into the report view when it's accessed, which dramatically increases its load time. Because of this, the front-end functionality for previewing, copying, and printing form letters in HTML requires its own (JavaScript-based) Markdown parsing library, while the e-mail functionality will use a separate (Python-based) Markdown parsing library. If form letters can be fetched from the server asynchronously, we will only need the backend to generate form-letter content.

**Questions for third parties:**
- Confirm: can GovDelivery TMS automatically convert HTML emails into plain-text only versions and send both in an email?
- Confirm: what are best practices for accessible HTML emails? I have two trains of thought on this: on the one hand, plain text feels easier to write content for in a way with less accessibility gotchas, but on the other hand, screen readers might prefer HTML because the semantic markup can help organize and convey information.

**Comment by ilodidoj** [comment]
@louh Thank you!! These are very good exploration, analysis and option to the issue we are trying to tackle for email response formatting. Just a little background on our existing portal design.  The front end single user, single report based; i.e. one report user only creating report and the edits are also in the front end before final submission to the server. Backend form/view is server based by design to work for either updates of report additional data, response via email, print, copy of the response for outlook email if the TMS is not working or alternate response needed.  Current design is email provider agnostic, we can use TMS, O365 or AWS without changing much of the email template selection on the portal report detail intake form.  We had explored TMS template earlier in the project, it seems this will require changes of all existing email templates to the TMS suggested template. Not sure, how the different version languages template will operate in this context. We can explore some proof of concept test to understand the actual TMS email HTML format support and level of effort for our full conversion of all existing report email templates.    CC: @randyabramson @blaughman @billyhunt
