### ISSUE TITLE
New Relic Errors

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1175]
New Relic Production Environment Error

"Error percentage > 10% for at least 5 minutes on 'CRT Portal (Production)"

- Started January 9, 2022 12:21 AM UTC
- Last errror on January 9, 2022 8:35 PM UTC

Details: https://alerts.newrelic.com/accounts/2734035/incidents/506998988

**Comment by blaughman** [comment]
Per Imran, "these are expected error for Internal Intake due to expired SSO session and SSO maintenance over the weekend.  Usually if you have portal internal page opened in the browser and left it for long period time it will eventually expired, this this cases it expired due to SSO maintenance.  All previous sessions expired. "  Closing this card.
