### ISSUE TITLE
Research - Additional Team Management Development (Phase Two)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1214]
## User story:
As a Product Owner, I want to know the requirements for displaying how many, and what type of, form letters each section sends out.

## Objective:
Prioritize additional development of the team management page.

## Key result:
Improve intake staff's ability to obtain necessary portal data.

## Ticket background:
The intake staff's first requested feature is to know how many, and what type of, form letters are sent in a given time period.

## Findings
[Design handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Aug-2021-Working-pages-(Copy)?node-id=738%3A7976)

**Default view**
<img width="1440" alt="Team Management Page - Future state default" src="https://user-images.githubusercontent.com/92807659/157684878-4dfb1e44-2901-4414-b1f9-5aa928f18bf4.png">

**Selected view**
<img width="1440" alt="Team Management Page - Future state v 1" src="https://user-images.githubusercontent.com/92807659/157684518-8957328f-2175-4947-b86b-14922439f56e.png">

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson 

Here is the draft design option for the future state of the Team Management page showing the number and type of form letters sent at a given time.

Let me know your thoughts and feedback.


![Future state v 1](https://user-images.githubusercontent.com/92807659/156239602-58ff548b-1606-4457-bd30-f7c08cd5c302.png)

**Comment by blaughman** [comment]
@chinelo-ikejimba @randyabramson This looks great.  Wondering if we can/should omit the auto-response?

**Comment by randyabramson** [comment]
@blaughman  interesting point about auto response...it will definitely be the biggest number by far and will mess up the scale. Yet, it's still an interesting number to know. Maybe just show it as a number?

@chinelo-ikejimba - BEAUTIFUL WORK. I do have some comments:

1. It might be interesting to ask the specialists if they'd prefer a separate tab for 'Section' vs. 'Individual Staff'. I think the layout you have here works for now, but when/if we have more reports...it might get very busy.

2. The italicized text looks small, but that might be because:
a. I'm old 
b. because it's a mock

3. Maybe the 'section activity' header should say 'Form letters sent'

4. On this 'section activity' card, italicized text can be simplified to say: 'the number of form letters sent by CRM between 03/30/2020 - Present'

5. Probably overthinking this, but I wonder if a 'print' button would be helpful on these cards?

Again, amazing fast and great work @chinelo-ikejimba

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson @billyhunt @eileen-nava

Here is the updated [Design handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Aug-2021-Working-pages-(Copy)?node-id=712%3A7559) per feedback from yesterday's Deep Dive session. Let me know if I missed any details.

<img width="1440" alt="Team Management Page - Future state v 1" src="https://user-images.githubusercontent.com/92807659/156786760-fa230c94-94b7-4221-90f3-94de44f6be30.png">

**Comment by eileen-nava** [comment]
Looks ~good~ rad to me! (~LGTM~ LRTM) 📻

**Comment by billyhunt** [comment]
Looks awesome.  A couple of questions.

* Is there anything that indicates what fields are required
* What does it look like when you land on the page before making a selection?
* What does is look like if there are no results for form letter types.  
* Do we still like the language "touched"?

**Comment by chinelo-ikejimba** [comment]
> Looks awesome. A couple of questions.
> 
> * Is there anything that indicates what fields are required
> * What does it look like when you land on the page before making a selection?
> * What does is look like if there are no results for form letter types.
> * Do we still like the language "touched"?
> * Currently it has a graph along the X axis that goes to 400.  Does this change or can we set a solid limit.
> * What happens if the bar is shorter than the number of reports.  EG 2.   Does the text live outside of the bar.

Great questions @billyhunt, I designed updates to answer your questions. 

For items not addressed in the updated designs:

- If there are no results for form letters, then those form letters will not appear in the graph.
- Because intake specialists regularly use the term "touched" as an umbrella-term for expressing all of their interactions on reports, it seems fine leave as is.

Let me know if you have more questions

**Comment by chinelo-ikejimba** [comment]
> > Looks awesome. A couple of questions.
> > 
> > * Is there anything that indicates what fields are required
> > * What does it look like when you land on the page before making a selection?
> > * What does is look like if there are no results for form letter types.
> > * Do we still like the language "touched"?
> > * Currently it has a graph along the X axis that goes to 400.  Does this change or can we set a solid limit.
> > * What happens if the bar is shorter than the number of reports.  EG 2.   Does the text live outside of the bar.
> 
> Great questions @billyhunt, I designed updates to answer your questions.
> 
> For items not addressed in the [updated designs](https://github.com/usdoj-crt/crt-portal-management/issues/1214#issue-1155597880):
> 
> * If there are no results for form letters, then those form letters will not appear in the graph.
> * Because intake specialists regularly use the term "touched" as an umbrella-term for expressing all of their interactions on reports, it seems fine leave as is.
> 
> Let me know if you have more questions

@billyhunt @eileen-nava @randyabramson @blaughman 
I updated the designs at the top of this ticket and in the design handoff to reflect the intake specialists suggested wording change from "Reports Touched" to "**Reports Accessed**".
<img width="1440" alt="Team Management Page - Future state v 1" src="https://user-images.githubusercontent.com/92807659/158862455-c036520e-1f43-49d7-a7fd-537cac9b869e.png">
