### ISSUE TITLE
Spike: Expand Frontend testing

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1282]
Our front end testing is not as robust as it could be.  We currently only test on chrome, and have not updated it in some time.  We should investigate ways to improve it, especially as we add new features.

**Comment by JackRyan1989** [comment]
Since we are already using Playwright for E2E testing, I suggest we use Playwright for frontend UI testing as well. I am currently using Playwright on the Beta ADA site, and have found it helpful for catching bugs and developing UI features. 
Please see the existing [ADR](https://github.com/usdoj-crt/beta-ada/blob/main/docs/playwright-decision-record.md) to understand my rationale for including Playwright.

**Comment by okkays** [comment]
Recording a few notes here - feel free to chime in/correct me if I've got it wrong:

- Regarding "general testing", we're planning to set up "bug bashing" sessions to identify immediate issues and keep an eye on categories of issues. If we identify common, persistent issues (such as broken links) often enough, we can allocate time towards addressing them automatically.
- Adding more classes of automated tests introduces a maintenance burden - the more useful the tests, the more often they break or fail unexpectedly (see #1447 and corresponding release issues for an example). It also adds time when we develop new features, as we have to tell our tests how to use the feature and exactly what to expect to happen.

That said, I'd recommend for overall testing:
  1. Looking into [screenshot testing](https://www.browserstack.com/guide/screenshot-testing) as part of our CI/CD. Ideally, we'd automatically see screenshots of the before and after in our pull requests, and be required to approve or deny them.
      - At first glance, it looks like we can do this as an extension of pa11y.
      - This can be fickle, especially if we introduce reactive features, but it also guarantees that PRs would have before-and-after screenshots of what has changed.
  1. We could take a stab at broken links in certain kinds of content. For example, by checking form letters and markdown.
      - We would only want to run these tests on dev/staging/production release, as you have to go to the urls to verify whether they're real, which can result in accidentally overloading those services if done too often or too quickly.

For Javascript code specifically, we should look at:
  1. First, outside of testing, making it possible to share code between modules. Currently each is minified separately, which means you can't share information between different files. We can add a modular system in tandem to the existing javascript.
  3. Whatever method we use to do that will help inform an appropriate unit testing library.
  4. We should then add unit tests to the existing frontend code as we migrate it to a modular system.

A concrete example of where this would be useful is in the toggle code - there's duplicate code in toggle vs toggle-all. If there's a bug in one, it'd have to be fixed in both places and, more importantly, the fixer would need to realize that the code is duplicated.
