### ISSUE TITLE
Localstack is getting parsing error.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1303]
When you run docker-compose down and then docker-compose up again, we get the following error from localstack.  

```urllib3.exceptions.LocationParseError: Failed to parse: http://localhost:4566http://localhost:4566/crt-portal/static/css/compiled/styles.css```

This is slowing our velocity.

**Comment by JackRyan1989** [comment]
Ok, so I did some testing and some research.

Looks like the issue is limited to version 0.14.3.1 of localstack. I can't replicate the issue using any of the following versions:
    - 0.12.20
    - 0.13.0
    - 0.13.1
    - 0.13.2
    - 0.13.3
    - 0.14.1
    - 0.14.2

I'm not sure why the issue is occurring with version 0.14.3.1 (latest), but one thing of note is that the Python version shipped by LocalStack is 3.10. Our docker container is using 3.9.12.

I don't think there is an issue with the persistence code, as it's still in place and has not been updated in any of the previous versions. 

Proposed solution: peg our localstack version to 0.14.2 until we can remove the Legacy Persistence feature. I'm not sure yet how or if LocalStack is going to provide a replacement for this feature in the Community version.

**Comment by billyhunt** [comment]
Great work @JackRyan1989.   CC @ilodidoj

**Comment by ilodidoj** [comment]
@JackRyan1989 @billyhunt @eileen-nava i have seen the issue on 0.14.2 version too. I still think we need to look at run.sh, docker compose and localstack settings.py to understand how and when the localstack bucket created for static files and how to access them after multiple stop and start of local stack. `localstack_main | [2022-06-03 17:54:44 +0000] [853] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | 2022-06-03T17:54:44.112:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | 2022-06-03T17:54:44.457:WARNING:localstack.services.infra: Persistence mechanism for community services (based on API calls record&replay) will be deprecated in versions 0.13.0 and above
localstack_main | 2022-06-03T17:54:44.544:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:34331
localstack_main | 2022-06-03T17:54:44.546:INFO:localstack.services.infra: Starting mock S3 service on http port 4566 ...
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
localstack_main |     scheme, auth, host, port, path, query, fragment = parse_url(url)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/url.py", line 394, in parse_url
localstack_main |     return six.raise_from(LocationParseError(source_url), None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main | urllib3.exceptions.LocationParseError: Failed to parse: http://localhost:4566http://localhost:4566/crt-portal/static/css/styles.css
localstack_main | 
`

**Comment by ilodidoj** [comment]
python version on each container (portal, db, clamav, localstack) should not be dependent on each other. We are making api call to localstack using the URL path localhost:4566.  I think this might be a access parameter or missing bucket issue. We can pair on this to dig up more.

**Comment by JackRyan1989** [comment]
@ilodidoj I think a pairing session would be helpful here. 

Personally I think we should also begin thinking about what to do about the Legacy Persistence flag since it's definitely going away. We're not going to be able to use the feature at all in the next version of LocalStack, so should we stop using it? That would solve this issue...

**Comment by billyhunt** [comment]
I downgraded localstack to 0.14.2 and it seems to be working fine.  I think the issue has to do with Localstack removing persistence from their free, "community" version.   https://github.com/localstack/localstack/releases

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/6232068/178031082-15caebe8-516f-4bee-86d8-3601b173a61f.png">


We probably want to explore long term replacing localstack with another option at some point.  The main localstack competitor is a tool called Minio (https://min.io/), Here is a link on how we might try to integrate. https://tomwojcik.com/posts/2020-09-18/local-s3-with-django-and-minio

**Comment by billyhunt** [comment]
this cannot be tested except locally, so feel free to move it along the swim lane.
