### ISSUE TITLE
Team Management Page has extra arrows on Microsoft Edge.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1321]
There are some extra arrows in the team management table on Microsoft Edge. Look right under the activity Log title and you can see it here. 

![image](https://user-images.githubusercontent.com/6232068/175129285-a88ad575-b4d8-4c61-989b-943bb9500f76.png)

**Comment by eileen-nava** [comment]
One additional piece of info: 

I see this bug when I use Microsoft Edge (version 103.0.1264.44) on my DOJ Windows machine, but not when I use Microsoft Edge (version 103.0.1264.44) on my DOJ Macbook.  Since the two machines have the same version of Microsoft Edge, and both versions are up to date, I don't think it's related to the Edge version.

I'll keep investigating.

**Comment by eileen-nava** [comment]
To test in UAT, navigate to the team management page on Chrome or Edge from a Windows machine.  Then, examine the table when it has no records in it, and ensure that the Activity log table doesn't have the extraneous arrows on the x axis.

**Comment by billyhunt** [comment]
Looks good in Windows to me.

**Comment by blaughman** [comment]
Arrows no longer appear on the page in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Arrows do not appear in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Arrows do not appear in Production.  Closing this card.
