### ISSUE TITLE
SPIKE - alternatives for export

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1366]
Recent data requests have resulted in timeouts and less than ideal situations for portal admin.  We're hoping to find alternatives to the current experience.  Add findings to this card once the spike is complete.

**Comment by randyabramson** [comment]
@billyhunt  - some examples of recently requested reports that we had to 'stitch together' because of the timeouts:

1. "I want to see all actions taken by a particular intake specialists from the past year"
2. "I want to see all reports that were referred from one section to another from the past year"
3. "breakdown of each type of form letter sent to complainants from a particular section between July 2020 and July 2021"

**Comment by billyhunt** [comment]
That's good. 

If it were me I might make it even more generic. Like:

* Every action for a given year. 
* every type of form letter sent with  its associated section and language for a given year. 

Do it's more extensible across different things you want to know. You would need to filter the data though. 

What do you think?

**Comment by randyabramson** [comment]
That works for me @billyhunt .

Thanks!

**Comment by billyhunt** [comment]
Tickets created for work.  Closing this card.
