### ISSUE TITLE
Page view duplicating filter tag

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1382]
## Summary

A DRS user indicated the page view filter tag was duplicating after hitting the 'back to all button.'

### Steps To Reproduce

1. From the view all table, select a report to view the detail page
2. Click the 'back to all' button
3. Look at the 'per page' filter tag
4. Select another report and view the detail page
5. Click the 'back to all' button
6. The 'per page' filter is now duplicated

If it's relevant, add browser or operating system where the error occurs.

### Expected Behavior
per_page is not a database query or search filter, should not display as a filter tag.

### Actual Behavior
The 'per page' filter tag duplicates every time a user views a complaint detail page and then returns to the view all table
![image](https://user-images.githubusercontent.com/52507395/186209030-74ab1c56-f544-43d4-b62b-acbfaf7e03e3.png)

## Suggested Actions
Suggestion made to remove the repeating per_page parameters.  Per page information already displayed in the data table where selection for record display is made.

## Acceptance Criteria
1) Given I am on the view all table
when I select a report and view the complaint detail page
AND then click the 'back to all' button
then I see no 'per page' filter tag displayed

2) Given I am on the view all table
when I select another report and view the complaint detail page
AND then click the 'back to all' button
then I only see no 'per page' filter tag

3) Correct per page value only show in the URL not during any of the filter selection tag when use apply filter.

**Comment by ilodidoj** [comment]
@blaughman @billyhunt I think we should totally remove the per_page display from the form, because this is not user select as filter input top area.  It's more display of recordset filter after the original filter display according to users selection. Once user select that record navigation area already provide the information on how many record selected to display, kind of redundant on the first display part.  We do have to check if we remove from the display does it have any impact on the actual query filter.

**Comment by blaughman** [comment]
Bug is no longer present in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Functions as expected in Production.  Closing this card.
