### ISSUE TITLE
Bug: Voting banner not displaying in dev when VOTING_MODE is True

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#1392]
## Summary

When Docker, Dev, Stage and Prod cloud environment VOTING_MODE is True; landing page should display voting banner.
Local dev docker is working as expected but not the dev cloud deployment.

### Steps To Reproduce

1. Follow the steps from here: https://github.com/usdoj-crt/crt-portal/blob/develop/docs/maintenance_or_infrequent_tasks.md#voting-mode to setup dev space
2. Default banner is displaying instead of Voting banner.

### Expected Behavior

Voting banner should display as primary.
Hate Crime banner should display as secondary.

### Actual Behavior
Only default Hate Crime banner displayed.

## Suggested Actions

Verify environment variable saved correctly in settings.py and template tag.

## Acceptance Criteria

Voting banner displayed when voting mode set to true in environment

**Comment by randyabramson** [comment]
@ilodidoj @blaughman 

is there an exta space showing on the banner between the word 'issues' and the comma?

Also, I believe we were going to change the url to https://civilrights.justice.gov/report/ (instead of https://civilrights.justice.gov) on https://crt-portal-django-stage.app.cloud.gov/voting-resources, but that might be on a different card.

**Comment by blaughman** [comment]
Appears as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Banner appearing as expected in Production in all languages.  Closing this card.
