### ISSUE TITLE
Revisit hate crimes page

### ISSUE THREAD

**Issue by Jacklynn** [usdoj-crt/crt-portal-management#592]
[placeholder, a lot of public users are checking "yes"]

**Comment by emilycryan** [comment]
Ok, after chatting with @randyabramson we decided to try a few things. Here's our first idea. 

There are two parts to this - a landing page banner that allows for more than one line of text and the moving of the hate crimes page to appear right after Step 1: Contact info and before the Primary Concern. The goal of both is to reroute the user to the FBI.gov site to file a hate crime. 

1. The user comes into the site via landing page. They can expand the banner to get a bit more info re. what constitutes a hate crime. This language and the layout is **not final** but it shows the idea behind open/closing like a drawer and routing the user prior to them starting to file a report. 
2. The user decides to forge ahead (or the user has come to the site and bypassed the landing page) and just after the contact page, step 1, we again, prompt them with similar content to the banner. If they feel they have been the victim of a hate crime, we will treat the experience just like we did with the original trafficking question where they are routed to fbi.gov directly. 

Thoughts/questions: 

- Do we want to include the popup modal like we do with trafficking before sending them to fbi.gov even though fbi.gov is a DOJ site?
- What do we do with the trafficking question? We can try to move that into the landing page but in this situation, we should not group it on the same page as the hate crime question. 
- We will need good content in both the banner and in the standalone page. Does this small amount of space afford enough information for the user to make a good decision?
- Is this too much? Too little? 
- How will we measure success of this test?

Screens/prototype: https://gsa.invisionapp.com/console/share/492TKJXHJA
CC @blaughman

**Comment by randyabramson** [comment]
Wow @emilycryan  you're quick!

Some thoughts:

1. On the banner, what if the word HATE CRIME was linked and activated the drop down when clicked? That would increase the chance that the user would read it? I think the 'learn more' is a bit out of view and might be overlooked.

2. For the 'to be considered a hate crime' text, maybe we should not use italics there? 

3. On the drop down, do we need to add 'if your situation does not fit the definition of a hate crime, you can still start a report here' or the like?

4. On the Hate Crime Primary Concern, I thought it would be part of the Primary Concern page with the other issues. Maybe your solution is better? Not sure.

5. Yes on modal

6. Trafficking - add to home page and later to education center

7. Measure success by seeing fewer non-actionable reports to CRM + an uptick in secondary review reports (since specialists will have more time to find them)

**Comment by randyabramson** [comment]
@emilycryan  @blaughman  one other thing...I am going through the full year of touchpoints and I see a bunch of feedback around:

1. What do I do in an emergency?
2. I want to talk to a real person

I'm not sure we want to load too much more into the hate crime banner, but maybe, 'in case of an emergency, call 911' might work here. That way could possibly send a bit less traffic to FBI. Just a thought.

**Comment by randyabramson** [comment]
@emilycryan  @blaughman 

Looking at Emily's mock again.

On the primary concern page, I have some thoughts:

1. We know the 'to be considered a hate crime' text was not being read and/or disregarded before. I think the text is fine, but we should figure out another way to display this so that it pops

2. I know this would break with our 'next' button convention, but would it make more sense to have these option buttons under the hate crime definition:
 - Report a hate crime on FBI.gov
 - Continue with other reports

**Comment by emilycryan** [comment]
@randyabramson I am just now seeing your comment from the 19th when I was out. The issue with your suggestion is that we already do what you're proposing - literally right below the main image area. And our users during research told us that it was pointless/extraneous and in their minds, unnecessary. So I really don't think we should include that twice, or even up higher at the top. See the screenshot:

![Screen Shot 2021-08-03 at 4 09 01 PM](https://user-images.githubusercontent.com/73443807/128079496-68cfc31a-2a4c-443f-9146-fdc81ee61d2f.png)

CC @blaughman Perhaps it's best to focus on the banner at the top and see what small thing we can do there but be OK with knowing that we won't be able to catch 100% of folks with that, regardless of what the UI looks like.

**Comment by emilycryan** [comment]
Here's another option to combine the items from both hate crime and trafficking which removes both from the flow. Content and design isn't final but it's a thought. 

https://gsa.invisionapp.com/console/share/492TKJXHJA/704734450

As I mentioned before, I'm not convinced this will do much in terms of handling the false reports and driving down numbers but I'm happy to try it. As an FYI we still have the dark blue section as mentioned above that contains the same info re. hate crimes and 911 just below the hero image. I'd recommend getting rid of that section completely since it's now duplicative for hate crime and not useful for 911.

CC @randyabramson @blaughman

**Comment by randyabramson** [comment]
@emilycryan  I really like what you did with the yellow banner.

Maybe we can start with that, measure and see if it makes an impact (knowing that only 50% of visits hit the home page. Would we consider running the yellow banner on the form as well?).

As for the hate crime part of the form, would we consider changing the 'next button' to say 'file other report types' or the like? It  might just be me, but I see a lot of real estate for hate crime explanation, then a 'report hate crime' button and a small 'next' button. Users might not know what the 'next' is in reference to or miss it completely. Again, this just might be me...

**Comment by emilycryan** [comment]
@randyabramson Honestly, we should get rid of the hate crime question once in the form because now we've addressed it twice AND it's not getting logged at this point. I'd recommend removing it and going straight from contact info to primary concern. 

Let's say a user actually *does* have something that may qualify. An intake specialist will be better positioned to suss that out on the back end and send it for secondary review rather than force every user to basically bypass this screen, which isn't doing anything anymore except forcing another step in an already long enough process. And it still feels terribly out of place - we don't hammer any other issue over user's heads like this so we need to get away from it here. At this point, it's just extra noise. 

CC @blaughman

**Comment by emilycryan** [comment]
And no, definitely **do not** run it on the form pages - we do not want distractions on individual steps of the form that will likely break it if a user happens to click it and bounce out. We need to refrain from putting it everywhere b/c people aren't getting it right. The more you show something that isn't relevant to a user, the more likely they are to start believing it is. And we already have a huge issue with that. @randyabramson @blaughman

**Comment by randyabramson** [comment]
@blaughman @emilycryan  - so, we can remove the hate crime question per Killian! 

@emilycryan I know that https://gsa.invisionapp.com/console/share/492TKJXHJA/704734450 was a rough first look. Do we want to continue to refine?

**Comment by randyabramson** [comment]
Leaving this open for Geronimo's work. I will also start going on translations.

**Comment by randyabramson** [comment]
Next step = Geronimo is going to update Emily's home page messaging mock cc: @emilycryan @blaughman

**Comment by randyabramson** [comment]
Meeting set to chat with Dan and Jim this week.
