### ISSUE TITLE
Landing Page Hover Highlight

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#900]
Aviva noted during testing that the example portion of the landing page is not appearing as expected.

Current Experience:
[https://app.zenhub.com/files/183258764/c9e477e6-e7fc-49ed-8dfa-65a7c76f9bb4/download](https://app.zenhub.com/files/183258764/c9e477e6-e7fc-49ed-8dfa-65a7c76f9bb4/download)

Expected Experience
[https://app.zenhub.com/files/183258764/d6ab0eab-1d82-4257-88b5-766c84f20fca/download](https://app.zenhub.com/files/183258764/d6ab0eab-1d82-4257-88b5-766c84f20fca/download)

**Comment by louh** [comment]
Pasting the above links as inline images since accessing those require signing into Zenhub.

Current experience:
![image](https://user-images.githubusercontent.com/2553268/135663102-c647dc35-ce98-4d94-98da-8597728f235e.png)

Expected experience:
![image](https://user-images.githubusercontent.com/2553268/135663196-d6e1f257-863b-4858-89ce-625d33800931.png)

**Comment by randyabramson** [comment]
@blaughman  is the header supposed to change as you mouse over the various topics? If so, I can't get this to happen after a hard refresh.
